### ISSUE TITLE
Window does not show anymore

### ISSUE THREAD

**Issue by gregduc** [W3D3/SteamAccountSwitcher#10]
Hi,
I just have an issue today with the exe. I lunched it as usual, but the windows do not show anymore. I tired to reinstall, clean all the settings file, and I keep running this issue...

Anyone have a solution?

Thank you

**Comment by W3D3** [comment]
Which version did you install and which operating system are you running it on?

Is there a process running in your task manager named "SteamAccountSwitcher. exe" after you start it?

**Comment by gregduc** [comment]
I'm running on Windows Familly x64

Yeah, I have the process. But I don't understand what happend... worked 
fine before, and decide to crash an stop working without any kind of 
warning...

**Comment by W3D3** [comment]
Try deleting all files and folders in `C:\Users\<Your Username>\AppData\Local\SteamAccountSwitcher` and then starting the program. Are you working on a multi-monitor setup?

**Comment by gregduc** [comment]
Solved. Thank you :)
