### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by Aidoboy** [W3D3/SteamAccountSwitcher#11]
@Skippeh turned off issue on his fork, so I can't ask where, but how can I compile this without paying for Visual Studio? Installshield says it doesn't work with the community edition.

**Comment by Skippeh** [comment]
You can safely remove the installshield project from the solution. It's only for creating the installer i'm pretty sure. I did and there were no problems atleast.

**Comment by Aidoboy** [comment]
Awesome, thanks!
