### ISSUE TITLE
How to open this app

### ISSUE THREAD

**Issue by ZeroTenFuras** [W3D3/SteamAccountSwitcher#15]
I have only isl file and i can't open it.

**Comment by W3D3** [comment]
@DzikuseQ I really don't know what you mean.
Did you install it using the installer?

**Comment by ZeroTenFuras** [comment]
Installer can't run. I can't open installation file

**Comment by W3D3** [comment]
The installer is a exe file though, no idea where you got an isl file from.
You sure that you got the latest release from here?
https://github.com/W3D3/SteamAccountSwitcher/releases/tag/1.1

**Comment by ZeroTenFuras** [comment]
In Steam Account Switcher Installer folder is only .isl file

**Comment by W3D3** [comment]
@DzikuseQ You have downloaded the source code for both the application and the installer.
If you don't want to build the project yourself, please just download the SteamAccountSwitcherSetup1.1.exe and run that.
Link: https://github.com/W3D3/SteamAccountSwitcher/releases/download/1.1/SteamAccountSwitcherSetup1.1.exe

**Comment by ZeroTenFuras** [comment]
Ok, thx. On first search ,,Steam account changer" is this, not installer. Sorry ;)
