### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by visualfanatic** [W3D3/SteamAccountSwitcher#2]
SteamAccountSwitcher would be perfect for me, if it would allow to sort the list, alphabetically or / and manually, by using drag'n'drop.

**Comment by W3D3** [comment]
Haven't worked on the project in a long time, but will look futher into this.

**Comment by W3D3** [comment]
Implemented in v2
https://github.com/W3D3/SteamAccountSwitcher2/commit/70113b6cfbea7406f0eb4f3507aa2eaa5f4b7b26
