### ISSUE TITLE
Import & Export

### ISSUE THREAD

**Issue by visualfanatic** [W3D3/SteamAccountSwitcher#4]
It would be lovely to have a feature to import & export accounts.

**Comment by Rottweiler** [comment]
If encryption methods differ on two different clients then the function would be useless, yes? If you have two clients with the same encryption methods then it's as simple as moving the storage file across (accounts.ini).

**Comment by W3D3** [comment]
This issue was moved to W3D3/SteamAccountSwitcher2#2
